name = "tulip"
version = "0.1.0"

description = "Tulip is a simple Gleam project for adding color to your terminal output. All 256 ANSI colors are supported."
licences = ["MIT"]
repository = { type = "github", user = "johnnymayodev", repo = "tulip" }
links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
